##########################Project_1#####################################
- name: Project_1
  hosts: Project_1

  tasks:
  - name: edit sshd_config
    handlers:
  - name: restart ssh
    service: sshd state=restarted
  - name: continue setup
    vars:
      - ansible_ssh_port : 1834
  
  tasks:
  - name: stop apparmor
    command: systemctl stop apparmor.service
  - name: disable apparmor 
    command: systemctl disable apparmor.service    

  - name: install ufw
    apt: pkg=ufw state=present update_cache=true

  - name: ufw enable
    ufw:
      state: enabled
      policy: deny
  - name: ufw allow ssh
    ufw:
      rule: allow
      port: 22
  - name: ufw allow port 80
    ufw:
      rule: allow
      port: 80
  - name: ufw allow port 8080
    ufw:
      rule: allow
      port: 8080
  - name: ufw allow port 1834
    ufw:
      rule: allow
      port: 1834
      
# - name: ssh 22:1834
#   lineinfile: dest=/etc/ssh/sshd_config
#                regexp=''
#                insertafter=OEF
#                line='Port 1834'
#  - name: restart ssh
#    command: systemctl restart ssh      