##########################Project_1#####################################
- name: Project_1
  hosts: Project_1

  tasks:
  - name: edit sshd_config
    handlers:
  - name: restart ssh
    service: sshd state=restarted
  - name: continue setup
    vars:
      - ansible_ssh_port : 1834
  
  tasks:
  - name: stop apparmor
    command: systemctl stop apparmor.service
  - name: disable apparmor 
    command: systemctl disable apparmor.service    

  - name: update
    command: apt update -y

  - name: install ufw
    apt: pkg=ufw state=present update_cache=true
  - name: install curl
    apt: pkg=curl state=present update_cache=true

  - name: ufw enable
    ufw:
      state: enabled
      policy: deny
  - name: ufw allow ssh
    ufw:
      rule: allow
      port: 22
  - name: ufw allow port 80
    ufw:
      rule: allow
      port: 80
  - name: ufw allow port 8080
    ufw:
      rule: allow
      port: 8080
  - name: ufw allow port 1834
    ufw:
      rule: allow
      port: 1834

# - name: ssh 22:1834
#   lineinfile: dest=/etc/ssh/sshd_config
#                regexp=''
#                insertafter=OEF
#                line='Port 1834'
#  - name: restart ssh
#    command: systemctl restart ssh    
  - name: install pip3  
    apt: pkg=pip3 state=present update_cache=true
  - name: install python3-pip  
    apt: pkg=python3-pip  state=present update_cache=true
  - name: install docker-compose  
    apt: pkg=docker-compose state=present update_cache=true  
    
  - name: /skillcloud-nginx
    command: mkdir skillcloud-nginx
        
  - name: restart ssh
    command: systemctl restart sshd

  - name: restart ufw
    command: ufw reload

  - name: reboot
    reboot:     